[patch.crates-io]
tiny-keccak = { git = "https://github.com/brevis-network/tiny-keccak", tag = "pico-patch-v1.0.0-keccak-v2.0.2" }

sha2 = { git = "https://github.com/brevis-network/hashes", tag = "pico-patch-v1.0.1-sha2-v0.10.8", package = "sha2" }
sha3 = { git = "https://github.com/brevis-network/hashes", tag = "pico-patch-v1.0.1-sha3-v0.10.8", package = "sha3" }

curve25519-dalek = { git = "https://github.com/brevis-network/curve25519-dalek", tag = "pico-patch-v1.0.1-curve25519-dalek-v4.1.3" }
bls12381 = { git = "https://github.com/brevis-network/bls12_381", tag = "pico-patch-v1.0.1-bls12_381-v0.8.0", package = "bls12_381" }
curve25519-dalek-ng = { git = "https://github.com/brevis-network/curve25519-dalek-ng", tag = "pico-patch-v1.0.1-curve25519-dalek-ng-v4.1.1" }
ed25519-consensus = { git = "https://github.com/brevis-network/ed25519-consensus", tag = "pico-patch-v1.0.1-ed25519-consensus-v2.1.0" }

ecdsa-core = { git = "https://github.com/brevis-network/signatures", tag = "pico-patch-v1.0.1-ecdsa-0.16.9", package = "ecdsa" }

secp256k1 = { git = "https://github.com/brevis-network/rust-secp256k1", tag = "pico-patch-v1.0.1-secp256k1-v0.29.1" }
substrate-bn = { git = "https://github.com/brevis-network/bn", tag = "pico-patch-v1.0.1-bn-v0.6.0" }
bigint = { git = "https://github.com/brevis-network/crypto-bigint", tag = "pico-patch-v1.0.0-bigint-v0.6.0", package = "crypto-bigint" }
