[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
succinct = ["run", "-p", "xtask", "--", "succinct", "--"]
zkm = ["run", "-p", "xtask", "--", "zkm", "--"]
risc0 = ["run", "-p", "xtask", "--", "risc0", "--"]
jolt = ["run", "-p", "xtask", "--", "jolt", "--"]
